version: '3.7'
volumes:
  data:
services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=typegraphqldb
    volumes:
      - data:/var/lib/postgres/data
